# Generated by Django 4.1.7 on 2023-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='status',
            field=models.CharField(blank=True, default='draft', max_length=100, null=True),
        ),
    ]
